export type Trade = {
  trade_id: string;
  article_id: string;
  article_title: string;
  article_summary: string;
  is_good_trade: boolean;
  instrument: string;
  direction: string;
  units: number;
  reasoning: string;
  confidence: number;
  timestamp: string;
  oanda_order_id: string;
  oanda_trade_id: string;
  trade_status: string;
};

export const mockTrades: Trade[] = [
  {
    trade_id: "a1b2c3d4-0001-4e5f-8a9b-000000000001",
    article_id: "art-001",
    article_title: "Fed signals rate hold amid cooling inflation data",
    article_summary: "The Federal Reserve indicated it will hold interest rates steady following softer-than-expected CPI figures, boosting confidence in USD stability.",
    is_good_trade: true,
    instrument: "EUR_USD",
    direction: "sell",
    units: 1000,
    reasoning: "USD strength expected following Fed rate hold signal. EUR likely to weaken against USD in short term.",
    confidence: 0.82,
    timestamp: "2026-05-31T09:14:23Z",
    oanda_order_id: "ORD-10001",
    oanda_trade_id: "TRD-20001",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0002-4e5f-8a9b-000000000002",
    article_id: "art-002",
    article_title: "UK GDP growth beats expectations in Q1 2026",
    article_summary: "Britain's economy expanded 0.7% in Q1 2026, surpassing analyst forecasts of 0.4%, driven by strong services sector performance.",
    is_good_trade: true,
    instrument: "GBP_USD",
    direction: "buy",
    units: 1500,
    reasoning: "GBP momentum supported by stronger-than-expected GDP. Likely short-term rally against USD.",
    confidence: 0.76,
    timestamp: "2026-05-30T14:32:10Z",
    oanda_order_id: "ORD-10002",
    oanda_trade_id: "TRD-20002",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0003-4e5f-8a9b-000000000003",
    article_id: "art-003",
    article_title: "Japan intervention fears grow as yen weakens past 158",
    article_summary: "The Japanese yen slid past the 158 mark against the dollar, reigniting speculation of government intervention to support the currency.",
    is_good_trade: false,
    instrument: "USD_JPY",
    direction: "buy",
    units: 0,
    reasoning: "Risk of sudden yen intervention makes this trade too volatile. Skipping to avoid adverse reversal.",
    confidence: 0.41,
    timestamp: "2026-05-30T08:05:55Z",
    oanda_order_id: "",
    oanda_trade_id: "",
    trade_status: "skipped",
  },
  {
    trade_id: "a1b2c3d4-0004-4e5f-8a9b-000000000004",
    article_id: "art-004",
    article_title: "ECB member hints at June rate cut as eurozone growth stalls",
    article_summary: "A senior ECB official suggested a rate cut in June is on the table after eurozone growth came in flat for a second consecutive quarter.",
    is_good_trade: true,
    instrument: "EUR_GBP",
    direction: "sell",
    units: 1200,
    reasoning: "ECB dovish pivot likely to weaken EUR relative to GBP, which has stronger macroeconomic backdrop.",
    confidence: 0.79,
    timestamp: "2026-05-29T11:48:30Z",
    oanda_order_id: "ORD-10004",
    oanda_trade_id: "TRD-20004",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0005-4e5f-8a9b-000000000005",
    article_id: "art-005",
    article_title: "Australian unemployment rises to 4.3%, missing forecasts",
    article_summary: "Australia's unemployment rate climbed to 4.3% in April, above the 4.1% expected, raising concerns about slowing domestic demand.",
    is_good_trade: true,
    instrument: "AUD_USD",
    direction: "sell",
    units: 2000,
    reasoning: "Weak jobs data increases RBA rate cut expectations, putting downward pressure on AUD.",
    confidence: 0.84,
    timestamp: "2026-05-29T03:22:14Z",
    oanda_order_id: "ORD-10005",
    oanda_trade_id: "TRD-20005",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0006-4e5f-8a9b-000000000006",
    article_id: "art-006",
    article_title: "Oil prices surge 4% on OPEC+ surprise production cut",
    article_summary: "OPEC+ announced an unexpected production cut of 500,000 barrels per day, sending crude prices sharply higher and boosting commodity currencies.",
    is_good_trade: true,
    instrument: "USD_CAD",
    direction: "sell",
    units: 1800,
    reasoning: "Higher oil prices benefit CAD as a petro-currency. USD/CAD expected to fall.",
    confidence: 0.77,
    timestamp: "2026-05-28T16:10:02Z",
    oanda_order_id: "ORD-10006",
    oanda_trade_id: "TRD-20006",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0007-4e5f-8a9b-000000000007",
    article_id: "art-007",
    article_title: "US-China trade tensions flare over new semiconductor restrictions",
    article_summary: "Washington announced additional restrictions on semiconductor exports to China, escalating trade tensions and triggering risk-off sentiment in markets.",
    is_good_trade: false,
    instrument: "USD_CNH",
    direction: "buy",
    units: 0,
    reasoning: "Trade war escalation creates unpredictable volatility. Not enough directional clarity to commit.",
    confidence: 0.38,
    timestamp: "2026-05-28T09:55:47Z",
    oanda_order_id: "",
    oanda_trade_id: "",
    trade_status: "skipped",
  },
  {
    trade_id: "a1b2c3d4-0008-4e5f-8a9b-000000000008",
    article_id: "art-008",
    article_title: "Swiss National Bank cuts rates by 25bps in surprise move",
    article_summary: "The SNB cut its policy rate to 0.75% in an unscheduled move, citing disinflationary pressures and a desire to curb CHF appreciation.",
    is_good_trade: true,
    instrument: "USD_CHF",
    direction: "buy",
    units: 1000,
    reasoning: "SNB rate cut weakens CHF. USD/CHF expected to rise as franc loses appeal.",
    confidence: 0.81,
    timestamp: "2026-05-27T10:30:00Z",
    oanda_order_id: "ORD-10008",
    oanda_trade_id: "TRD-20008",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0009-4e5f-8a9b-000000000009",
    article_id: "art-009",
    article_title: "Eurozone inflation falls to 1.8%, below ECB target",
    article_summary: "Flash estimates show eurozone CPI dropped to 1.8% in May, falling below the ECB's 2% target for the first time in three years.",
    is_good_trade: true,
    instrument: "EUR_USD",
    direction: "sell",
    units: 1300,
    reasoning: "Below-target inflation reinforces ECB rate cut narrative, weakening EUR against USD.",
    confidence: 0.75,
    timestamp: "2026-05-27T07:15:33Z",
    oanda_order_id: "ORD-10009",
    oanda_trade_id: "TRD-20009",
    trade_status: "open",
  },
  {
    trade_id: "a1b2c3d4-0010-4e5f-8a9b-000000000010",
    article_id: "art-010",
    article_title: "New Zealand central bank holds rates, signals no cuts until 2027",
    article_summary: "The RBNZ kept rates at 5.5% and pushed back its rate cut timeline to 2027, surprising markets that had priced in cuts later this year.",
    is_good_trade: true,
    instrument: "NZD_USD",
    direction: "buy",
    units: 900,
    reasoning: "Hawkish RBNZ surprise boosts NZD. Market repricing of rate path favors NZD appreciation.",
    confidence: 0.73,
    timestamp: "2026-05-26T22:00:11Z",
    oanda_order_id: "ORD-10010",
    oanda_trade_id: "TRD-20010",
    trade_status: "open",
  },
];
